security:
  oauth2:
    client:
      clientId: 613356575897859
      clientSecret: 7ec375f76bcc3b28ab9fdb8bdb6028a0
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me


facebook:
  client:
    clientId: 613356575897859
    clientSecret: 7ec375f76bcc3b28ab9fdb8bdb6028a0
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me


github:
  client:
    clientId: c43188f38c932176507f
    clientSecret: 028f11366678e3695f076d0d10a360e39e9b3eb0
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
